# If the system is a NTP server then we will add firewall rules.
- name: Opening firewall port for NTP Server
  block:
# Use this rule if the ntp_allow range has been defined.
  - name: Chrony.FirewallD - Allow specific subnet network range
    ansible.posix.firewalld:
      service: ntp
      source: "{{ item }}"
      permanent: yes
      state: enabled
    ignore_errors: True
    loop: "{{ chrony_server.allow }}"
    when: chrony_server.allow is defined
    notify: FirewallD - Reload

# Use this rule if the ntp_allow range has not been defined.
  - name: Chrony.FirewallD - Allow all subnet ranges
    ansible.posix.firewalld:
      service: ntp
      permanent: yes
      state: enabled
    ignore_errors: True
    when: chrony_server.allow is not defined
    notify: FirewallD - Reload

  when: service.chrony is defined or '"service-chrony" in tags'

# If the system is not an NTP server we ensure the port is closed. Remember that if you set a desired state (as above) you must un-set it afterwards.
- name: Chrony.FirewallD - Ensure NTP server port is closed
  ansible.posix.firewalld:
    service: ntp
    state: disabled
  ignore_errors: True
  when: service.chrony is not defined or '"service-chrony" not in tags'
  notify: FirewallD - Reload

# - name: Chrony.FirewallD - Start and Enable service
#   ansible.builtin.service:
#     name: firewalld
#     state: started
#     enabled: yes