- name: Chrony.Install - Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ package_install }}"
  notify: Chrony - Enable

- name: Chrony.Install - Deploy Configuration file from template
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: "{{ configfile }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0644'
    backup: true
  notify: Chrony - Restart

- name: Chrony.Install - Deploy Keys file from template
  ansible.builtin.template:
    src: chrony.keys.j2
    dest: "{{ keyfile }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0600'
    backup: true
  notify: Chrony - Restart

- name: Chrony.Install - Ensure Dump Directory is created
  ansible.builtin.file:
    path: "{{ dumponexit_path }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0750'
  when:
    - dumponexit_enabled | bool
    - dumponexit_path is defined
