- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: True
  with_items: "{{ package_install }}"

- name: Chrony - Copy Configuration files
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: "{{ chrony_config }}"
    owner: root
    group: root
    mode: 0644
  notify: Chrony Restart

- name: Chrony - Enable Service
  ansible.builtin.service:
    name: "{{ chrony_service }}"
    enabled: yes