---
# tasks file for ntp::main

- name: Chrony.Main - Gather facts from server
  ansible.builtin.setup:
    filter: ansible_default_ipv4.address

- name: Chrony.Main - Gather service facts from server
  ansible.builtin.service_facts:

# Context
# -------
# The context section is used to load variables. This has been built in a specific
 #  order so that subsequent variable files override earlier variables.
# This generates a specicifity very similar to what we see in Chef.
# The order is as follows:
#  - OS Family (i.e: Debian, RedHat)
#  - Distribution (i.e: RedHat Enterprise, CentOS, Ubuntu)
#  - LSB name (i.e: Raspbian) - only applicable to Debian-based OS's,
#     and primarily needed to support Raspbian on Raspberry Pi's as its the only place Raspbian is specified
#  - Distribution-Version (i.e: Debian-10)

# Remember these are all lowercase

- name: Chrony.Main - Load Distribution specific variables file
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "context/{{ ansible_distribution | lower }}/main.yml" # RedHat, CentOS, Debian, Ubuntu, etc
      skip: true

# This deals with os-specific variabiles. Store them in /var/os/___.yml
- name: Chrony.Main - Load OS specific variables file
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - files:
        - "context/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version | lower }}.yml" # centos/7.yml
        - "context/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.yml" # debian/wheezy.yml
      skip: true

# We load these in blocks to that we dont have to copy every single varialbe into files with a higher specicity.
# Remember:
#   - Variables in more specific files completely overwrite variables loaded before it.
#   - Variables do not concatonate. You must specify the whole variable again.
# -------

# Remove old NTPq packages - we don't need these any more with Chrony.
- name: Chrony.Main - Handoff to PreFlight task
  ansible.builtin.include_tasks: preflight.yml

# Install Chrony and configure
- name: Chrony.Main - Handoff to Install task
  ansible.builtin.include_tasks: install.yml

# Configure firewall to allow outbound Chrony connections for the server.
- name: Chrony.Main - Hand off to FirewallD task
  ansible.builtin.include_tasks: firewall/firewalld.yml
  when: # Only execute this task if firewalld is deteted as installed.
    - "'firewalld.service' in services"
    - ansible_facts.services['firewalld.service'].state == 'running'
