---
# handlers file for ntp
- name: Chrony Restart
  ansible.builtin.service:
    name: "{{ chrony_service }}"
    state: restarted

- name: FirewallD Restart Service
  ansible.builtin.service:
    name: firewalld
    state: reloaded