---
  dependency:
    name: galaxy
  driver:
    name: docker
  lint: |
    set -e
    yamllint .
    ansible-lint
    flake8
  platforms:
    - name: centos7
      image: centos:7
      command: /sbin/init
      tmpfs:
        - /run
        - /tmp
      capabilities:
        - SYS_ADMIN
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      exposed_ports:
        - 123/udp
      published_ports:
        - 0.0.0.0:8123:123/udp
    - name: centos8
      image: centos:8
      command: /sbin/init
      tmpfs:
        - /run
        - /tmp
      capabilities:
        - SYS_ADMIN
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      exposed_ports:
        - 123/udp
      published_ports:
        - 0.0.0.0:8124:123/udp
    - name: ubuntu
      image: ubuntu:focal
      # command: /sbin/init
      # tmpfs:
      #   - /run
      #   - /tmp
      # capabilities:
      #   - SYS_ADMIN
      # volumes:
      #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
      exposed_ports:
        - 123/udp
      published_ports:
        - 0.0.0.0:8125:123/udp
  provisioner:
    name: ansible
  verifier:
    name: ansible 